apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-deployment
  labels:
    app: scc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scc
  template:
    metadata:
      labels:
        app: scc
    spec:
      containers:
        - name: scc
          image: luisferreira23/test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: DB_HOST
              value: "postgresql-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "1234567890"
            - name: DB_NAME
              value: "Test1"
            - name: DATABASE_URL
              value: "postgresql://postgres:1234567890@postgresql-service:5432/Test1"
