apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-deployment
  labels:
    app: scc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scc
  template:
    metadata:
      labels:
        app: scc
    spec:
      containers:
        - name: scc
          image: luisferreira23/test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
