FROM node:22.13.1-alpine
WORKDIR /tasks-api
COPY ./services/shared .
RUN npm install --omit=dev
RUN npm install -g nodemon
COPY ./services/src/tasks .
#DEV ONLY
#COPY .env .
#DEV ONLY
CMD ["npm", "start"]