FROM node:22.13.1-alpine AS builder
WORKDIR /tasks-api
COPY services/shared ./
RUN npm install --omit=dev

FROM node:22.13.1-alpine
WORKDIR /tasks-api
COPY --from=builder /tasks-api/node_modules ./node_modules
COPY services/shared ./
COPY services/src/tasks .
CMD ["npm", "start"]