FROM node:22.13.1-alpine
WORKDIR /gateway-api
COPY services/shared/package*.json ./
RUN npm install --omit=dev
RUN npm install -g nodemon
COPY services/gateway .
COPY services/shared .
#DEV ONLY
COPY .env .
#DEV ONLY
CMD ["npm", "start"]